# Generated by Django 4.2 on 2023-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grant_Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("timeline", models.DateField(auto_now_add=True)),
                ("date_of_submission", models.DateTimeField(auto_now_add=True)),
                ("Foundation", models.CharField(max_length=255)),
                ("Amount_Requested", models.IntegerField()),
                ("Amount_Received", models.IntegerField()),
                ("Awarded_Dated", models.DateTimeField(auto_now_add=True)),
                ("Payment_Date", models.DateTimeField(auto_now_add=True)),
                ("Purpose", models.CharField(max_length=300)),
                ("POC_NAME", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=255)),
                ("Year_Awarded", models.DateField()),
            ],
        ),
    ]
