# Generated by Django 4.2 on 2023-04-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=30)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grant_app.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_name", models.CharField(max_length=30)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grant_app.priority",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grant_Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("timeline", models.DateField(auto_now_add=True)),
                ("date_of_submission", models.DateTimeField(auto_now_add=True)),
                ("Foundation", models.CharField(max_length=255)),
                ("Amount_Requested", models.IntegerField()),
                ("Amount_Received", models.IntegerField()),
                ("Awarded_Dated", models.DateTimeField(auto_now_add=True)),
                ("Payment_Date", models.DateTimeField(auto_now_add=True)),
                ("Purpose", models.CharField(max_length=300)),
                ("POC_NAME", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=255)),
                ("Year_Awarded", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grant_app.category",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grant_app.priority",
                    ),
                ),
            ],
        ),
    ]
