# Generated by Django 4.2 on 2023-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grant_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant_management",
            name="Year_Awarded",
            field=models.DateField(auto_now_add=True),
        ),
    ]
